name: "Bug Report"
description: "Please report the issue so it can be fixed."
title: "[BUG] - {{Short description}}"
labels:
  - bug
assignees: []

body:
  - type: input
    id: problem_description
    attributes:
      label: "Problem Description"
      description: "Please describe the problem in detail so that we can understand what exactly is happening."
      placeholder: "Enter a short summary of the problem..."

  - type: textarea
    id: reproduction
    attributes:
      label: "Steps for reproduction"
      description: "Please provide detailed steps to reproduce the error."
